// Generator for simple ResourceView wrappers
const fs = require('fs');
const path = require('path');

const VIEWS_DIR = '/home/z/my-project/src/components/views';

const VIEWS = {
  leads: {
    entity: 'leads',
    title: 'Leads',
    singular: 'Lead',
    description: 'Track every prospect. Convert leads into customers.',
    icon: 'User',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'source', label: 'Source', type: 'select', options: ['manual', 'referral', 'website', 'social', 'cold_call', 'other'] },
      { key: 'status', label: 'Status', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Won', 'Lost'] },
      { key: 'stage', label: 'Stage', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Won', 'Lost'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
      { key: 'value', label: 'Value (₹)', type: 'number', showPaise: false },
      { key: 'tags', label: 'Tags', type: 'tags' },
      { key: 'notes', label: 'Notes', type: 'textarea', width: 'full' },
    ],
    filterableByStatus: ['New', 'Contacted', 'Qualified', 'Won', 'Lost'],
  },
  customers: {
    entity: 'customers',
    title: 'Customers',
    singular: 'Customer',
    description: 'Your paying customers and their lifetime value.',
    icon: 'Users',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['individual', 'business'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'churned'] },
      { key: 'tags', label: 'Tags', type: 'tags' },
    ],
    filterableByStatus: ['active', 'inactive', 'churned'],
  },
  contacts: {
    entity: 'contacts',
    title: 'Contacts',
    singular: 'Contact',
    description: 'All business contacts — buyers, partners, vendors.',
    icon: 'UsersRound',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'isPrimary', label: 'Primary', type: 'select', options: ['false', 'true'] },
      { key: 'tags', label: 'Tags', type: 'tags' },
    ],
  },
  companies: {
    entity: 'companies',
    title: 'Companies',
    singular: 'Company',
    description: 'Organisations you do business with.',
    icon: 'Building2',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'address', label: 'Address', type: 'textarea', width: 'full' },
    ],
  },
  deals: {
    entity: 'deals',
    title: 'Deals',
    singular: 'Deal',
    description: 'Open opportunities with potential revenue.',
    icon: 'Handshake',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, width: 'full' },
      { key: 'value', label: 'Value (₹)', type: 'number' },
      { key: 'stage', label: 'Stage', type: 'select', options: ['New', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'] },
      { key: 'probability', label: 'Probability (%)', type: 'number' },
      { key: 'expectedCloseDate', label: 'Expected Close', type: 'date', showDate: true },
    ],
    filterableByStatus: ['New', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'],
  },
  tasks: {
    entity: 'tasks',
    title: 'Tasks',
    singular: 'Task',
    description: 'All actionable work — yours and your team\'s.',
    icon: 'CheckSquare',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, width: 'full' },
      { key: 'description', label: 'Description', type: 'textarea', width: 'full' },
      { key: 'type', label: 'Type', type: 'select', options: ['general', 'follow_up', 'collection', 'visit', 'call', 'custom'] },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'done', 'overdue', 'cancelled'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
      { key: 'dueDate', label: 'Due Date', type: 'date', showDate: true },
    ],
    filterableByStatus: ['open', 'in_progress', 'done', 'overdue', 'cancelled'],
  },
  followups: {
    entity: 'followups',
    title: 'Follow-ups',
    singular: 'Follow-up',
    description: 'Scheduled follow-ups with leads and customers.',
    icon: 'CalendarClock',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, width: 'full' },
      { key: 'dueAt', label: 'Due At', type: 'datetime-local', showTimeAgo: false },
      { key: 'outcome', label: 'Outcome', type: 'text' },
      { key: 'completedAt', label: 'Completed At', type: 'datetime-local' },
    ],
  },
  calls: {
    entity: 'calls',
    title: 'Calls',
    singular: 'Call',
    description: 'Telecalling activity log with outcomes.',
    icon: 'Phone',
    fields: [
      { key: 'direction', label: 'Direction', type: 'select', options: ['inbound', 'outbound'] },
      { key: 'status', label: 'Status', type: 'select', options: ['planned', 'connected', 'missed', 'failed'] },
      { key: 'outcome', label: 'Outcome', type: 'text' },
      { key: 'duration', label: 'Duration (s)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', width: 'full' },
      { key: 'nextFollowUpAt', label: 'Next Follow-up', type: 'datetime-local' },
    ],
    filterableByStatus: ['planned', 'connected', 'missed', 'failed'],
  },
  meetings: {
    entity: 'meetings',
    title: 'Meetings',
    singular: 'Meeting',
    description: 'Scheduled meetings with attendees.',
    icon: 'CalendarDays',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, width: 'full' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'scheduledAt', label: 'Start', type: 'datetime-local' },
      { key: 'endedAt', label: 'End', type: 'datetime-local' },
      { key: 'notes', label: 'Notes', type: 'textarea', width: 'full' },
      { key: 'outcome', label: 'Outcome', type: 'text' },
    ],
  },
  activities: {
    entity: 'activities',
    title: 'Activities',
    singular: 'Activity',
    description: 'Log of all customer and lead interactions.',
    icon: 'ListTodo',
    fields: [
      { key: 'type', label: 'Type', type: 'select', options: ['call', 'meeting', 'email', 'note', 'task', 'visit', 'other'] },
      { key: 'title', label: 'Title', type: 'text', required: true, width: 'full' },
      { key: 'description', label: 'Description', type: 'textarea', width: 'full' },
      { key: 'outcome', label: 'Outcome', type: 'text' },
      { key: 'scheduledAt', label: 'Scheduled At', type: 'datetime-local' },
      { key: 'completedAt', label: 'Completed At', type: 'datetime-local' },
    ],
    filterableByStatus: ['call', 'meeting', 'email', 'note', 'task', 'visit', 'other'],
  },
  quotations: {
    entity: 'quotations',
    title: 'Quotations',
    singular: 'Quotation',
    description: 'Price quotes sent to leads and customers.',
    icon: 'FileText',
    fields: [
      { key: 'subject', label: 'Subject', type: 'text', required: true, width: 'full' },
      { key: 'number', label: 'Number', type: 'text' },
      { key: 'totalAmount', label: 'Total (paise)', type: 'number', showPaise: true },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'sent', 'approved', 'rejected', 'expired', 'converted'] },
      { key: 'validTill', label: 'Valid Till', type: 'date', showDate: true },
    ],
    filterableByStatus: ['draft', 'sent', 'approved', 'rejected', 'expired', 'converted'],
  },
  orders: {
    entity: 'orders',
    title: 'Orders',
    singular: 'Order',
    description: 'Confirmed orders from customers.',
    icon: 'ShoppingCart',
    fields: [
      { key: 'number', label: 'Number', type: 'text' },
      { key: 'totalAmount', label: 'Total (paise)', type: 'number', showPaise: true },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned'] },
    ],
    filterableByStatus: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned'],
  },
  payments: {
    entity: 'payments',
    title: 'Payments',
    singular: 'Payment',
    description: 'Money received from customers.',
    icon: 'Wallet',
    fields: [
      { key: 'number', label: 'Number', type: 'text' },
      { key: 'amount', label: 'Amount (paise)', type: 'number', showPaise: true },
      { key: 'method', label: 'Method', type: 'select', options: ['cash', 'upi', 'card', 'bank', 'cheque', 'other'] },
      { key: 'status', label: 'Status', type: 'select', options: ['received', 'pending', 'failed', 'refunded'] },
      { key: 'paidAt', label: 'Paid At', type: 'datetime-local', showTimeAgo: true },
    ],
    filterableByStatus: ['received', 'pending', 'failed', 'refunded'],
  },
  invoices: {
    entity: 'invoices',
    title: 'Invoices',
    singular: 'Invoice',
    description: 'Bills raised on customers.',
    icon: 'Receipt',
    fields: [
      { key: 'number', label: 'Number', type: 'text' },
      { key: 'totalAmount', label: 'Total (paise)', type: 'number', showPaise: true },
      { key: 'status', label: 'Status', type: 'select', options: ['unpaid', 'partial', 'paid', 'overdue', 'cancelled'] },
      { key: 'dueDate', label: 'Due Date', type: 'date', showDate: true },
    ],
    filterableByStatus: ['unpaid', 'partial', 'paid', 'overdue', 'cancelled'],
  },
  expenses: {
    entity: 'expenses',
    title: 'Expenses',
    singular: 'Expense',
    description: 'Money going out of the business.',
    icon: 'TrendingDown',
    fields: [
      { key: 'description', label: 'Description', type: 'text', required: true, width: 'full' },
      { key: 'amount', label: 'Amount (paise)', type: 'number', showPaise: true },
      { key: 'category', label: 'Category', type: 'select', options: ['general', 'office', 'travel', 'utilities', 'salaries', 'marketing', 'inventory', 'rent', 'other'] },
      { key: 'paidAt', label: 'Paid At', type: 'datetime-local', showTimeAgo: true },
    ],
    filterableByStatus: ['general', 'office', 'travel', 'utilities', 'salaries', 'marketing', 'inventory', 'rent', 'other'],
  },
  employees: {
    entity: 'employees',
    title: 'Employees',
    singular: 'Employee',
    description: 'Your team — including non-login staff.',
    icon: 'Briefcase',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['full_time', 'part_time', 'contract', 'intern'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { key: 'salary', label: 'Salary (₹/mo)', type: 'number' },
      { key: 'joinedAt', label: 'Joined At', type: 'date', showDate: true },
    ],
    filterableByStatus: ['active', 'inactive'],
  },
  departments: {
    entity: 'departments',
    title: 'Departments',
    singular: 'Department',
    description: 'Departments within your business.',
    icon: 'Building',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
    ],
  },
  attendance: {
    entity: 'attendance',
    title: 'Attendance',
    singular: 'Attendance',
    description: 'Daily attendance records for employees.',
    icon: 'CalendarCheck',
    fields: [
      { key: 'employeeId', label: 'Employee ID', type: 'text' },
      { key: 'date', label: 'Date', type: 'date', showDate: true },
      { key: 'checkIn', label: 'Check In', type: 'datetime-local' },
      { key: 'checkOut', label: 'Check Out', type: 'datetime-local' },
      { key: 'status', label: 'Status', type: 'select', options: ['present', 'absent', 'leave', 'half_day', 'late'] },
      { key: 'notes', label: 'Notes', type: 'textarea', width: 'full' },
    ],
    filterableByStatus: ['present', 'absent', 'leave', 'half_day', 'late'],
  },
  leaves: {
    entity: 'leaves',
    title: 'Leaves',
    singular: 'Leave',
    description: 'Employee leave applications.',
    icon: 'Plane',
    fields: [
      { key: 'employeeId', label: 'Employee ID', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['casual', 'sick', 'earned', 'unpaid', 'other'] },
      { key: 'startDate', label: 'Start', type: 'date', showDate: true },
      { key: 'endDate', label: 'End', type: 'date', showDate: true },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected', 'cancelled'] },
      { key: 'reason', label: 'Reason', type: 'textarea', width: 'full' },
    ],
    filterableByStatus: ['pending', 'approved', 'rejected', 'cancelled'],
  },
  products: {
    entity: 'products',
    title: 'Products & Services',
    singular: 'Product',
    description: 'Things you sell — physical or service.',
    icon: 'Package',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['product', 'service'] },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'price', label: 'Price (paise)', type: 'number', showPaise: true },
      { key: 'cost', label: 'Cost (paise)', type: 'number', showPaise: true },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'taxRate', label: 'Tax Rate (%)', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea', width: 'full' },
    ],
    filterableByStatus: ['product', 'service'],
  },
  warehouses: {
    entity: 'warehouses',
    title: 'Warehouses',
    singular: 'Warehouse',
    description: 'Storage locations for inventory.',
    icon: 'Warehouse',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'location', label: 'Location', type: 'text' },
    ],
  },
  suppliers: {
    entity: 'suppliers',
    title: 'Suppliers',
    singular: 'Supplier',
    description: 'Vendors who supply your inventory.',
    icon: 'Truck',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'address', label: 'Address', type: 'textarea', width: 'full' },
    ],
  },
  'purchase-orders': {
    entity: 'purchase_orders',
    title: 'Purchase Orders',
    singular: 'PO',
    description: 'Purchase orders raised on suppliers.',
    icon: 'ClipboardList',
    fields: [
      { key: 'number', label: 'Number', type: 'text' },
      { key: 'supplierId', label: 'Supplier ID', type: 'text' },
      { key: 'totalAmount', label: 'Total (paise)', type: 'number', showPaise: true },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'sent', 'received', 'cancelled'] },
    ],
    filterableByStatus: ['draft', 'sent', 'received', 'cancelled'],
  },
  campaigns: {
    entity: 'campaigns',
    title: 'Campaigns',
    singular: 'Campaign',
    description: 'Marketing campaigns by channel.',
    icon: 'Megaphone',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['manual', 'email', 'social', 'web', 'sms'] },
      { key: 'status', label: 'Status', type: 'select', options: ['planned', 'active', 'paused', 'completed'] },
      { key: 'budget', label: 'Budget (paise)', type: 'number', showPaise: true },
      { key: 'spent', label: 'Spent (paise)', type: 'number', showPaise: true },
      { key: 'startDate', label: 'Start', type: 'date', showDate: true },
      { key: 'endDate', label: 'End', type: 'date', showDate: true },
    ],
    filterableByStatus: ['planned', 'active', 'paused', 'completed'],
  },
  'lead-sources': {
    entity: 'lead_sources',
    title: 'Lead Sources',
    singular: 'Lead Source',
    description: 'Channels that bring you leads.',
    icon: 'Globe',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'type', label: 'Type', type: 'select', options: ['manual', 'web', 'api', 'csv', 'referral'] },
      { key: 'isActive', label: 'Active', type: 'select', options: ['true', 'false'] },
    ],
  },
  automations: {
    entity: 'automations',
    title: 'Automations',
    singular: 'Automation',
    description: 'Trigger → Conditions → Actions workflow rules.',
    icon: 'Workflow',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'trigger', label: 'Trigger', type: 'select', options: ['new_lead', 'quotation_inactive', 'payment_overdue', 'low_stock', 'customer_inactive', 'manual', 'scheduled'] },
      { key: 'requiresApproval', label: 'Requires Approval', type: 'select', options: ['false', 'true'] },
      { key: 'isActive', label: 'Active', type: 'select', options: ['true', 'false'] },
    ],
    filterableByStatus: ['new_lead', 'quotation_inactive', 'payment_overdue', 'low_stock', 'customer_inactive', 'manual', 'scheduled'],
  },
  'custom-fields': {
    entity: 'custom_fields',
    title: 'Custom Fields',
    singular: 'Custom Field',
    description: 'Add custom fields to any entity.',
    icon: 'Settings2',
    fields: [
      { key: 'entity', label: 'Entity', type: 'select', options: ['lead', 'customer', 'contact', 'deal', 'quotation', 'order', 'task'] },
      { key: 'key', label: 'Key', type: 'text', required: true },
      { key: 'label', label: 'Label', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['text', 'number', 'date', 'select', 'multiselect', 'boolean'] },
      { key: 'isRequired', label: 'Required', type: 'select', options: ['false', 'true'] },
      { key: 'isActive', label: 'Active', type: 'select', options: ['true', 'false'] },
    ],
    filterableByStatus: ['lead', 'customer', 'contact', 'deal', 'quotation', 'order', 'task'],
  },
  pipelines: {
    entity: 'pipelines',
    title: 'Pipelines',
    singular: 'Pipeline',
    description: 'Sales pipelines with configurable stages.',
    icon: 'GitBranch',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, width: 'full' },
      { key: 'entity', label: 'Entity', type: 'select', options: ['lead', 'deal', 'customer'] },
      { key: 'stages', label: 'Stages (CSV)', type: 'tags', width: 'full' },
      { key: 'isDefault', label: 'Default', type: 'select', options: ['false', 'true'] },
    ],
    filterableByStatus: ['lead', 'deal', 'customer'],
  },
  'stock': {
    entity: 'stock',
    title: 'Stock Levels',
    singular: 'Stock Item',
    description: 'Current inventory levels with reorder points.',
    icon: 'Boxes',
    fields: [
      { key: 'productId', label: 'Product ID', type: 'text', required: true },
      { key: 'warehouseId', label: 'Warehouse ID', type: 'text' },
      { key: 'quantity', label: 'Quantity', type: 'number' },
      { key: 'reorderLevel', label: 'Reorder Level', type: 'number' },
    ],
  },
};

const ICON_IMPORTS = {
  User: 'User',
  Users: 'Users',
  UsersRound: 'UsersRound',
  Building2: 'Building2',
  Building: 'Building',
  Handshake: 'Handshake',
  CheckSquare: 'CheckSquare',
  CalendarClock: 'CalendarClock',
  Phone: 'Phone',
  CalendarDays: 'CalendarDays',
  ListTodo: 'ListTodo',
  FileText: 'FileText',
  ShoppingCart: 'ShoppingCart',
  Wallet: 'Wallet',
  Receipt: 'Receipt',
  TrendingDown: 'TrendingDown',
  Briefcase: 'Briefcase',
  CalendarCheck: 'CalendarCheck',
  Plane: 'Plane',
  Package: 'Package',
  Warehouse: 'Warehouse',
  Boxes: 'Boxes',
  Truck: 'Truck',
  ClipboardList: 'ClipboardList',
  Megaphone: 'Megaphone',
  Globe: 'Globe',
  Workflow: 'Workflow',
  Settings2: 'Settings2',
  GitBranch: 'GitBranch',
};

let count = 0;
for (const [name, cfg] of Object.entries(VIEWS)) {
  const icon = ICON_IMPORTS[cfg.icon] || 'Package';
  const content = `'use client';

import { ResourceView, type ResourceConfig } from '@/components/resource-view';
import { ${icon} } from 'lucide-react';

const config: ResourceConfig = ${JSON.stringify(cfg, null, 2).replace(/"icon":\s*".*"/, `icon: ${icon}`)};

export function ${pascalCase(name)}View() {
  return <ResourceView config={config} />;
}
`;
  const filename = path.join(VIEWS_DIR, `${name}.tsx`);
  fs.writeFileSync(filename, content);
  count++;
}

function pascalCase(s) {
  return s.split(/[-_]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

console.log(`Generated ${count} view files.`);
